# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "aws" {
  region = "us-east-1"
  default_tags {
    tags = {
      email = "forrestmillerj@gmail.com"
      managedWith = "terraform"
    }
  }
}
