# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
variable "environment" {
    type = string
}

variable "app_prefix" {
    type = string
    default = "aws-infra"
}

variable "namespace" {
    type = string
    default = "fomiller"
}

variable "asset_name" {
    type = string
}
