apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: twitch-credentials
spec:
  refreshInterval: 12h
  secretStoreRef:
    name: twitch-credentials
    kind: ClusterSecretStore
  target:
    name: twitch-credentials
    creationPolicy: Owner
  data:
  - secretKey: client_secret
    remoteRef:
      key: dev/fomiller/chat-stat/twitch-credentials #AWS Secrets Manager secret name
      property: client_secret #AWS Secrets Manager secret key
  - secretKey: client_id
    remoteRef:
      key: dev/fomiller/chat-stat/twitch-credentials #AWS Secrets Manager secret name
      property: client_id #AWS Secrets Manager secret key


