version: 2
jobs:
  aws login:
    docker:
      - image: fomiller/megatainer:latest
    environment:
      AWS_PROFILE: default
    steps:
      - run:
          command: |
              aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID --profile $AWS_PROFILE
              aws configure set aws_secret_access_key $AWS_SECRET_KEY_ACCESS_KEY --profile $AWS_PROFILE
      - persist_to_workspace:
          root: ../
          paths:
            - ./*

  terraform init and validate:
    docker:
      - image: fomiller/megatainer:latest
    steps:
      - checkout
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: ../
      - run:
          working_directory: us-east-1/dev/
          command: |
            terragrunt run-all validate
      - persist_to_workspace:
          root: ../
          paths:
            - ./*

  terraform plan:
    docker:
      - image: fomiller/megatainer:latest
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: ../
      - run:
          working_directory: us-east-1/dev/
          command: |
            terragrunt run-all plan
      - persist_to_workspace:
          root: ../
          paths:
            - ./*

  terraform apply:
    docker:
      - image: fomiller/megatainer:latest
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: ../
      - run:
          working_directory: us-east-1/dev/
          command: |
            terragrunt run-all apply --terragrunt-non-interactive
          
workflows:
  version: 2
  Terraform Deploy:
    jobs:
      - aws login
      - terraform init and validate:
          context:
            - aws-credentials
          requires:
            - aws login
      - terraform plan:
          context:
            - aws-credentials
          requires:
            - terraform init and validate
      - terraform apply:
          context:
            - aws-credentials
          requires:
            - terraform plan
