# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: php-apache
#   namespace: fomiller
# spec:
#   ports:
#   - port: 80
#   selector:
#     run: php-apache
#
---
apiVersion: v1
kind: Service
metadata:
  name: argocd
  namespace: argocd
spec:
  ports:
  - port: 80
  selector:
    run: argocd
