apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: karpenter
spec:
  amiFamily: AL2
  role: FomillerEksNodesGroups
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: owned
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: owned
        kubernetes.io/cluster/fomiller-cluster: owned
  tags:
    karpenter.sh/discovery: fomiller-cluster
---
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: karpenter
spec:
  template:
    spec:
      nodeClassRef:
        name: default
      requirements:
        - key: "karpenter.k8s.aws/instance-category"
          operator: In
          values: ["c", "m", "r"]
        - key: "karpenter.k8s.aws/instance-cpu"
          operator: In
          values: ["4", "8", "16", "32"]
        - key: "karpenter.k8s.aws/instance-hypervisor"
          operator: In
          values: ["nitro"]
        - key: "karpenter.k8s.aws/instance-generation"
          operator: Gt
          values: ["2"]
  limits:
    cpu: 1000
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 30s
