# .github/workflows/dev-deploy.yml

name: 'Terragrunt Deploy'
  
on:
  push:
    paths:
      - '.github/**'
      - 'modules/**'
      - 'infra/**'
    branches:
      - '*'
      - 'feature/*'
      - '!main'
      - '!master'
        
# env:
#   TF_VAR_gmail_congocoon_pass: ${{ secrets.GMAIL_CONGOCOON_PASSWORD}}
#   AWS_ACCESS_KEY_ID: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
#   AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
#   AWS_ACCOUNT_ID: ${{ secrets.DEV_AWS_ACCOUNT }}
#   AWS_DEPLOYER_ROLE: ${{ secrets.AWS_DEPLOYER_ROLE }}
#   AWS_DEFAULT_REGION: us-east-1
#   AWS_DEFAULT_OUTPUT: json
#   TG_VERSION: v0.42.8
#   TF_VERSION: latest
#   INFRA_DIR: infra/us-east-1/dev

    
jobs:
  deploy-infra:
    uses: fomiller-org/gh-actions/.github/workflows/terragrunt.yaml@v1
    with:
      environment: dev
    secrets: 
      aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
      aws-secret-access-KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
      aws-account-id: ${{ secrets.DEV_AWS_ACCOUNT }}
      aws-deployer-role: ${{ secrets.AWS_DEPLOYER_ROLE }}
